# Site settings
course_name: Topics in Encrypted Systems
course_description: "The growing area of encrypted systems combines cryptographic advancements with systems so that the overall design can compute directly on ciphertexts without decrypting. Encrypted systems ensure privacy in settings where users outsource the computation on their sensitive data to third-party machines, e.g., cloud service. In this class we will focus on encrypted databases, an area that gained traction and represents an excellent candidate, if not the sole one, for querying encrypted data in real-world applications.  

We will start by briefly covering basic notions of security under this setting as well as necessary concepts from applied cryptography, then spend the majority of the class covering the evolution of the field of encrypted databases from its conception to its current state-of-the-art solutions. This class will focus on both the theory and the practice of encrypted databases and will introduce not only practical cryptographic designs but also recent attacks in the area. The chosen papers cover topics including, but not limited to: searchable encryption, dynamic designs, forward security, constructions for range queries, leakage attacks on keyword search, leakage attacks on range queries, leakage attacks on property-preserving encryption, lower bounds on secure constructions, encrypted databases in a distributed setting, mitigations based on frequency-smoothing, and constructions for solid state drives. Participants are expected to read the assigned research papers, present a paper in class, and deliver a final project tailored to their interests."
course_semester: "Fall 2021"

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://anonymous3354.github.io/" # the base hostname & protocol for your site

schoolname: "George Mason University"
schoolurl: "https://gmu.edu"
twitter_username: GeorgeMasonU 

address: |
   Department of Computer Science
   Nguyen Engineering Building
   4400 University Drive
   Fairfax, VA 22030

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: false
    lectures:
        output: false
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
