# Site settings
course_name: Theory of Computation
course_description: <p>This course will cover topics in computability theory and complexity theory. Specifically, we will cover automata theory, Turing machines, decidability, P and NP, polynomial-time reductions, circuit complexity, randomized computation and extraction, and proof systems. There is no required text; we will rely very heavily on the lecture notes found in the links below. These notes adapted from Prof. Jonathan Katz's and Prof. Dov Gordon's notes, which can be found under the "links" section on the right.</p>

course_semester: "Fall 2021"

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://anonymous3354.github.io/" # the base hostname & protocol for your site

schoolname: "George Mason University"
schoolurl: "https://gmu.edu"
twitter_username: GeorgeMasonU 

address: |
   Department of Computer Science
   Nguyen Engineering Building
   4400 University Drive
   Fairfax, VA 22030

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: false
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: ""
    values:
      layout: ""
